copy Common\Serialization\bin\MathEx.ExternalBallistic.Serialization.dll c:\BallisticCalculator\
copy Common\Serialization\bin\MathEx.ExternalBallistic.Serialization.pdb c:\BallisticCalculator\
copy Common\Math\bin\MathEx.ExternalBallistic.dll c:\BallisticCalculator\
copy Common\Math\bin\MathEx.ExternalBallistic.pdb c:\BallisticCalculator\
copy Common\ConnectivityData\bin\Gehtsoft.BallisticCalculator.Connectivity.dll c:\BallisticCalculator\
copy Common\ConnectivityData\bin\Gehtsoft.BallisticCalculator.Connectivity.pdb c:\BallisticCalculator\

copy Windows\Serialization.Windows\bin\MathEx.ExternalBallistic.Serialization.Windows.dll c:\BallisticCalculator\
copy Windows\Serialization.Windows\bin\MathEx.ExternalBallistic.Serialization.Windows.pdb c:\BallisticCalculator\
copy Windows\Connectivity\bin\Gehtsoft.BallisticCalculator.Connectivity.Windows.pdb c:\BallisticCalculator\
copy Windows\Connectivity\bin\Gehtsoft.BallisticCalculator.Connectivity.Windows.dll c:\BallisticCalculator\
copy Windows\Connectivity\bin\Gehtsoft.BallisticCalculator.Connectivity.Windows.pdb c:\BallisticCalculator\
copy Windows\Calculator\bin\Gehtsoft.BallisticCalculator.Reticle.dll c:\BallisticCalculator\
copy Windows\Calculator\bin\Gehtsoft.BallisticCalculator.Reticle.pdb c:\BallisticCalculator\
copy Windows\Calculator\bin\Gehtsoft.BallisticCalculator.UI.dll c:\BallisticCalculator\
copy Windows\Calculator\bin\Gehtsoft.BallisticCalculator.UI.pdb c:\BallisticCalculator\
copy Windows\Calculator\bin\Gehtsoft.BallisticCalculator.UI.TypeControls.dll c:\BallisticCalculator\
copy Windows\Calculator\bin\Gehtsoft.BallisticCalculator.UI.TypeControls.pdb c:\BallisticCalculator\
copy Windows\ReticleEditor\bin\ReticleEditor.exe c:\BallisticCalculator\
copy Windows\ReticleEditor\bin\ReticleEditor.pdb c:\BallisticCalculator\
copy Windows\Calculator\bin\BallisticCalculator.exe c:\BallisticCalculator\
copy Windows\Calculator\bin\BallisticCalculator.pdb c:\BallisticCalculator\
copy Windows\3rdparty\ZedGraph.dll c:\BallisticCalculator\
