#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Gehtsoft.BallisticCalculator.Resource", IsApplication=true)]

namespace Gehtsoft.BallisticCalculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int dd_lblsBeaufortWindScale = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int dd_lblsBeaufortWindScaleDescription = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int dd_lbls_Angle_imperial = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int dd_lbls_Angle_metric = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int dd_lbls_Distance_imperial = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int dd_lbls_Distance_metric = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int dd_lbls_Drag_Table = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int dd_lbls_Energy_imperial = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int dd_lbls_Energy_metric = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int dd_lbls_Pressure_imperial = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int dd_lbls_Pressure_metric = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int dd_lbls_Temperature_imperial = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int dd_lbls_Temperature_metric = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int dd_lbls_Units = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int dd_lbls_Velocity_imperial = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int dd_lbls_Velocity_metric = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int dd_lbls_Weight_imperial = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int dd_lbls_Weight_metric = 2131034119;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07004f
			public const int anglePickerWindDirection = 2131165263;
			
			// aapt resource value: 0x7f070031
			public const int btnBallisticTable = 2131165233;
			
			// aapt resource value: 0x7f070033
			public const int btnCommunicateDesktop = 2131165235;
			
			// aapt resource value: 0x7f07002e
			public const int btnSelectTrace = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int btnSetAtmo = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int btnSetWind = 2131165232;
			
			// aapt resource value: 0x7f070034
			public const int btnSettings = 2131165236;
			
			// aapt resource value: 0x7f070032
			public const int btnSingleShot = 2131165234;
			
			// aapt resource value: 0x7f07005d
			public const int buttonAdd = 2131165277;
			
			// aapt resource value: 0x7f070037
			public const int buttonAltitudeUnits = 2131165239;
			
			// aapt resource value: 0x7f07004b
			public const int buttonBeaufortChart = 2131165259;
			
			// aapt resource value: 0x7f07001d
			public const int buttonBulletDiameterUnits = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int buttonBulletLengthUnits = 2131165216;
			
			// aapt resource value: 0x7f07000d
			public const int buttonBulletWeightUnits = 2131165197;
			
			// aapt resource value: 0x7f070055
			public const int buttonCalculateShot = 2131165269;
			
			// aapt resource value: 0x7f070008
			public const int buttonCancel = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int buttonCommunicate = 2131165191;
			
			// aapt resource value: 0x7f070013
			public const int buttonDragTable = 2131165203;
			
			// aapt resource value: 0x7f07005e
			public const int buttonEdit = 2131165278;
			
			// aapt resource value: 0x7f07002c
			public const int buttonHorizontalClickUnits = 2131165228;
			
			// aapt resource value: 0x7f070040
			public const int buttonHumidityUnits = 2131165248;
			
			// aapt resource value: 0x7f070010
			public const int buttonMuzzleVelocityUnits = 2131165200;
			
			// aapt resource value: 0x7f07003a
			public const int buttonPressureUnits = 2131165242;
			
			// aapt resource value: 0x7f070023
			public const int buttonRiflingUnits = 2131165219;
			
			// aapt resource value: 0x7f07002d
			public const int buttonSave = 2131165229;
			
			// aapt resource value: 0x7f07005c
			public const int buttonSelect = 2131165276;
			
			// aapt resource value: 0x7f070047
			public const int buttonStepSingleShotUnits = 2131165255;
			
			// aapt resource value: 0x7f070044
			public const int buttonStepUnits = 2131165252;
			
			// aapt resource value: 0x7f07003d
			public const int buttonTemperatureUnits = 2131165245;
			
			// aapt resource value: 0x7f070042
			public const int buttonUnits = 2131165250;
			
			// aapt resource value: 0x7f070041
			public const int buttonUseGPS = 2131165249;
			
			// aapt resource value: 0x7f070029
			public const int buttonVerticalClickUnits = 2131165225;
			
			// aapt resource value: 0x7f07004e
			public const int buttonWindDirectionUnits = 2131165262;
			
			// aapt resource value: 0x7f07004a
			public const int buttonWindSpeedUnits = 2131165258;
			
			// aapt resource value: 0x7f070016
			public const int buttonZeroDistanceUnits = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int buttonZeroHeightUnits = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int checkBoxCalculateSpinDrift = 2131165210;
			
			// aapt resource value: 0x7f070043
			public const int editStep = 2131165251;
			
			// aapt resource value: 0x7f070046
			public const int editStepSingleShot = 2131165254;
			
			// aapt resource value: 0x7f070036
			public const int editTextAltitude = 2131165238;
			
			// aapt resource value: 0x7f070012
			public const int editTextBallisticCoefficient = 2131165202;
			
			// aapt resource value: 0x7f07001c
			public const int editTextBulletDiameter = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int editTextBulletLength = 2131165215;
			
			// aapt resource value: 0x7f07000c
			public const int editTextBulletWeight = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int editTextDesktopAddress = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int editTextDesktopPort = 2131165187;
			
			// aapt resource value: 0x7f07002b
			public const int editTextHorizontalClick = 2131165227;
			
			// aapt resource value: 0x7f07003f
			public const int editTextHumidity = 2131165247;
			
			// aapt resource value: 0x7f07000f
			public const int editTextMuzzleVelocity = 2131165199;
			
			// aapt resource value: 0x7f070039
			public const int editTextPressure = 2131165241;
			
			// aapt resource value: 0x7f070022
			public const int editTextRifling = 2131165218;
			
			// aapt resource value: 0x7f07003c
			public const int editTextTemperature = 2131165244;
			
			// aapt resource value: 0x7f07000a
			public const int editTextTraceName = 2131165194;
			
			// aapt resource value: 0x7f070028
			public const int editTextVerticalClick = 2131165224;
			
			// aapt resource value: 0x7f07004d
			public const int editTextWindDirection = 2131165261;
			
			// aapt resource value: 0x7f070049
			public const int editTextWindSpeed = 2131165257;
			
			// aapt resource value: 0x7f070015
			public const int editTextZeroDistance = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int editTextZeroHeight = 2131165208;
			
			// aapt resource value: 0x7f07005b
			public const int listViewTraces = 2131165275;
			
			// aapt resource value: 0x7f070052
			public const int numberPickerRange = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int numberPickerWind = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int numberPickerWindDirection = 2131165268;
			
			// aapt resource value: 0x7f070006
			public const int radioButtonJoinTraces = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int radioButtonReplaceTraces = 2131165189;
			
			// aapt resource value: 0x7f070025
			public const int radioButtonRiflingHandLeft = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int radioButtonRiflingHandRight = 2131165222;
			
			// aapt resource value: 0x7f070024
			public const int radioGroupRiflingHand = 2131165220;
			
			// aapt resource value: 0x7f070004
			public const int radioGroupTraceAction = 2131165188;
			
			// aapt resource value: 0x7f070045
			public const int stepSingleShot = 2131165253;
			
			// aapt resource value: 0x7f070001
			public const int tableLayoutBallisticTable = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int tableLayoutBallisticTableHeader = 2131165184;
			
			// aapt resource value: 0x7f070035
			public const int textViewAltitude = 2131165237;
			
			// aapt resource value: 0x7f070011
			public const int textViewBallisticCoefficient = 2131165201;
			
			// aapt resource value: 0x7f07001b
			public const int textViewBulletDiameter = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int textViewBulletLength = 2131165214;
			
			// aapt resource value: 0x7f07000b
			public const int textViewBulletWeight = 2131165195;
			
			// aapt resource value: 0x7f070056
			public const int textViewCorrectionAngleUnits = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int textViewElevationCorrectionAngle = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int textViewElevationCorrectionClicks = 2131165272;
			
			// aapt resource value: 0x7f07002a
			public const int textViewHorizontalClick = 2131165226;
			
			// aapt resource value: 0x7f07003e
			public const int textViewHumidity = 2131165246;
			
			// aapt resource value: 0x7f07000e
			public const int textViewMuzzleVelocity = 2131165198;
			
			// aapt resource value: 0x7f070038
			public const int textViewPressure = 2131165240;
			
			// aapt resource value: 0x7f070050
			public const int textViewRange = 2131165264;
			
			// aapt resource value: 0x7f070021
			public const int textViewRifling = 2131165217;
			
			// aapt resource value: 0x7f07003b
			public const int textViewTemperature = 2131165243;
			
			// aapt resource value: 0x7f070009
			public const int textViewTraceName = 2131165193;
			
			// aapt resource value: 0x7f070027
			public const int textViewVerticalClick = 2131165223;
			
			// aapt resource value: 0x7f070051
			public const int textViewWind = 2131165265;
			
			// aapt resource value: 0x7f070059
			public const int textViewWindCorrectionAngle = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int textViewWindCorrectionClicks = 2131165274;
			
			// aapt resource value: 0x7f07004c
			public const int textViewWindDirection = 2131165260;
			
			// aapt resource value: 0x7f070048
			public const int textViewWindSpeed = 2131165256;
			
			// aapt resource value: 0x7f070014
			public const int textViewZeroDistance = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int textViewZeroHeight = 2131165207;
			
			// aapt resource value: 0x7f07005f
			public const int windSpeedLsit = 2131165279;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BallisticTable = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CommunicateDesktop = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditTrace = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SetAtmo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Settings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SetWind = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SingleShot = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Traces = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int WindSpeedList = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int btn_lbl_Add = 2130968587;
			
			// aapt resource value: 0x7f040024
			public const int btn_lbl_Back = 2130968612;
			
			// aapt resource value: 0x7f040006
			public const int btn_lbl_BallisticTable = 2130968582;
			
			// aapt resource value: 0x7f040039
			public const int btn_lbl_BeaufortChart = 2130968633;
			
			// aapt resource value: 0x7f04001c
			public const int btn_lbl_Calculate = 2130968604;
			
			// aapt resource value: 0x7f04000d
			public const int btn_lbl_Cancel = 2130968589;
			
			// aapt resource value: 0x7f040025
			public const int btn_lbl_ChooseUnits = 2130968613;
			
			// aapt resource value: 0x7f040023
			public const int btn_lbl_Communicate = 2130968611;
			
			// aapt resource value: 0x7f040008
			public const int btn_lbl_CommunicateDesktop = 2130968584;
			
			// aapt resource value: 0x7f04003a
			public const int btn_lbl_Continue = 2130968634;
			
			// aapt resource value: 0x7f04000c
			public const int btn_lbl_Edit = 2130968588;
			
			// aapt resource value: 0x7f040036
			public const int btn_lbl_Save = 2130968630;
			
			// aapt resource value: 0x7f04000a
			public const int btn_lbl_Select = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int btn_lbl_SelectTrace = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int btn_lbl_SetAtmosphere = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int btn_lbl_SetWind = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int btn_lbl_Settings = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int btn_lbl_SingleShot = 2130968583;
			
			// aapt resource value: 0x7f040040
			public const int btn_lbl_StopUsingSensors = 2130968640;
			
			// aapt resource value: 0x7f04003f
			public const int btn_lbl_UseSensors = 2130968639;
			
			// aapt resource value: 0x7f04001b
			public const int btn_lbl_changeStepRate = 2130968603;
			
			// aapt resource value: 0x7f04002e
			public const int cb_lbl_CalculateSpinDrift = 2130968622;
			
			// aapt resource value: 0x7f040026
			public const int dd_prompt_Units = 2130968614;
			
			// aapt resource value: 0x7f04003b
			public const int edit_hint_Altitude = 2130968635;
			
			// aapt resource value: 0x7f04002a
			public const int edit_hint_BallisticCoefficient = 2130968618;
			
			// aapt resource value: 0x7f04002f
			public const int edit_hint_BulletDiameter = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int edit_hint_BulletLength = 2130968624;
			
			// aapt resource value: 0x7f040028
			public const int edit_hint_BulletWeight = 2130968616;
			
			// aapt resource value: 0x7f04001f
			public const int edit_hint_DesktopAdress = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int edit_hint_DesktopPort = 2130968608;
			
			// aapt resource value: 0x7f040035
			public const int edit_hint_HorizontalClick = 2130968629;
			
			// aapt resource value: 0x7f04003e
			public const int edit_hint_Humidity = 2130968638;
			
			// aapt resource value: 0x7f040029
			public const int edit_hint_MuzzleVelocity = 2130968617;
			
			// aapt resource value: 0x7f04003c
			public const int edit_hint_Pressure = 2130968636;
			
			// aapt resource value: 0x7f040031
			public const int edit_hint_Rifling = 2130968625;
			
			// aapt resource value: 0x7f04003d
			public const int edit_hint_Temperature = 2130968637;
			
			// aapt resource value: 0x7f040027
			public const int edit_hint_TraceName = 2130968615;
			
			// aapt resource value: 0x7f040034
			public const int edit_hint_VerticalClick = 2130968628;
			
			// aapt resource value: 0x7f040038
			public const int edit_hint_WindDirection = 2130968632;
			
			// aapt resource value: 0x7f040037
			public const int edit_hint_WindSpeed = 2130968631;
			
			// aapt resource value: 0x7f04002b
			public const int edit_hint_ZeroDistance = 2130968619;
			
			// aapt resource value: 0x7f04002d
			public const int edit_hint_ZeroElevationAngle = 2130968621;
			
			// aapt resource value: 0x7f04002c
			public const int edit_hint_ZeroHeight = 2130968620;
			
			// aapt resource value: 0x7f040002
			public const int lbl_EditTraceActivity = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int lbl_MainActivity = 2130968577;
			
			// aapt resource value: 0x7f040046
			public const int msg_AgainstWind = 2130968646;
			
			// aapt resource value: 0x7f040041
			public const int msg_InternalError = 2130968641;
			
			// aapt resource value: 0x7f040047
			public const int msg_InvalidUri = 2130968647;
			
			// aapt resource value: 0x7f040049
			public const int msg_LoadTracesFail = 2130968649;
			
			// aapt resource value: 0x7f040048
			public const int msg_LoadedNTraces = 2130968648;
			
			// aapt resource value: 0x7f040043
			public const int msg_PressBackToExit = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int msg_SensorWaitTimeout = 2130968644;
			
			// aapt resource value: 0x7f04004a
			public const int msg_ServerIsNotFound = 2130968650;
			
			// aapt resource value: 0x7f040045
			public const int msg_TowardTarget = 2130968645;
			
			// aapt resource value: 0x7f040042
			public const int msg_TraceNotSelected = 2130968642;
			
			// aapt resource value: 0x7f040021
			public const int rb_lbl_JoinTraces = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int rb_lbl_ReplaceTraces = 2130968610;
			
			// aapt resource value: 0x7f040032
			public const int rb_lbl_RiflingLeftHand = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int rb_lbl_RiflingRightHand = 2130968627;
			
			// aapt resource value: 0x7f040014
			public const int tv_lbl_Clicks = 2130968596;
			
			// aapt resource value: 0x7f04001d
			public const int tv_lbl_ElevationV = 2130968605;
			
			// aapt resource value: 0x7f040011
			public const int tv_lbl_Energy = 2130968593;
			
			// aapt resource value: 0x7f040017
			public const int tv_lbl_FlightTime = 2130968599;
			
			// aapt resource value: 0x7f040013
			public const int tv_lbl_Hold = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int tv_lbl_Mach = 2130968592;
			
			// aapt resource value: 0x7f040018
			public const int tv_lbl_OGW = 2130968600;
			
			// aapt resource value: 0x7f040012
			public const int tv_lbl_Path = 2130968594;
			
			// aapt resource value: 0x7f04000e
			public const int tv_lbl_Range = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int tv_lbl_Velocity = 2130968591;
			
			// aapt resource value: 0x7f040019
			public const int tv_lbl_Wind = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int tv_lbl_WindAdjustment = 2130968598;
			
			// aapt resource value: 0x7f04001a
			public const int tv_lbl_WindDirectionClock = 2130968602;
			
			// aapt resource value: 0x7f04001e
			public const int tv_lbl_WindV = 2130968606;
			
			// aapt resource value: 0x7f040015
			public const int tv_lbl_Windage = 2130968597;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MainMenuButton = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int UnitsButton = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
